### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ajnart** [ajnart/subs#8]
Small docker container that can be deployed easily. I want it to use virtually no memory. The website can be static as of now

**Comment by pypeaday** [comment]
It's hardly worth even a PR but if you wanted to add a compose file for users to play with...

```
services:
  subs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
```

Then just `docker compose up -d` and no one has to think about building the image themselves
